### ISSUE TITLE
/api/v1/host/list 的API是不是改了， 现在获取不到 hosts了

### ISSUE THREAD

**Issue by winmin** [DVKunion/Collar#1]

**Comment by DVKunion** [comment]
看API没有变动，可能是token过期了，稍晚些我确认一下。

**Comment by winmin** [comment]
> 看API没有变动，可能是token过期了，稍晚些我确认一下。

应该不是token过期，我新建的token

**Comment by DVKunion** [comment]
确认了一下，现在主机列表需要获取分组权限，百川平台的api-token应该获取不到这个分组权限（杀了一个开发祭天）。等他们上班了我去对线让他们修一下。

感谢提交 🙏

**Comment by winmin** [comment]
> 

ok

**Comment by DVKunion** [comment]
already fix at v1.0.0-Beta3, thanks again @WinMin
